--- #YAML:1.0
name:                Module-Versions-Report
version:             1.03
abstract:            report versions of all modules in memory
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
