--- #YAML:1.0
name:               Module-Versions-Report
version:            1.06
abstract:           report versions of all modules in memory
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
